### ISSUE TITLE
trWav_clu variable not created

### ISSUE THREAD

**Issue by WeissShahaf** [flatironinstitute/ironclust#35]
Every time i try to use ironclust, even at default settings, after completing irc spikesort, and trying to run irc manual i get the following error:

 irc manual 20191004_GL485_dual_septum_exvivo_g0_t0.imec1.ap_imec3b_staggered.prm

Reference to non-existent field 'trWav_clu'.
Error in irc>plot_tnWav_clu_ (line 6203)
trWav_clu = ifeq_(P.fWav_raw_show,
S_clu.trWav_raw_clu,
S_clu.trWav_clu);%S_clu.trWav_clu%S_clu.tmrWav_clu
Error in irc>plot_FigWav_ (line 5909)
    S_fig = plot_tnWav_clu_(S_fig, P); %do
    this after plotSpk_
Error in irc>manual_ (line 5545)
S0 = plot_FigWav_(S0); % hFigWav %do this
after for ordering
Error in irc (line 294)
    manual_(P);

**Comment by WeissShahaf** [comment]
fSpatialMask_clu is missing when using the vanilla irc commit pull.



Sorting took 255.3s for GL383_20190815_sleep_plusmaze3_g0_t0.imec0.ap_imec3b_staggered.prm
Saving 0.UserData to GL383_20190815_sleep_plusmaze3_g0_t0.imec0.ap_imec3b_staggered_jrc.mat...
Saving a struct to GL383_20190815_sleep_plusmaze3_g0_t0.imec0.ap_imec3b_staggered_jrc.mat...
	took 3.9s.
Full parameter settings are exported to GL383_20190815_sleep_plusmaze3_g0_t0.imec0.ap_imec3b_staggered_full.prm
Reference to non-existent field 'fSpatialMask_clu'.
Error in irc>describe_ (line 5332)
    csDesc{end+1} = sprintf('    fSpatialMask_clu        %d', P.fSpatialMask_clu);
Error in irc>run_irc_ (line 28111)
detect_(P); sort_(P, 0); describe_(P.vcFile_prm);
Error in irc (line 230)
        run_irc_(P); 





then when trying to use the manual GUI, variable trWav_clu is missing

Reference to non-existent field 'trWav_clu'.
Error in irc>plot_tnWav_clu_ (line 6203)
trWav_clu = ifeq_(P.fWav_raw_show, S_clu.trWav_raw_clu, S_clu.trWav_clu);%S_clu.trWav_clu%S_clu.tmrWav_clu
Error in irc>plot_FigWav_ (line 5909)
    S_fig = plot_tnWav_clu_(S_fig, P); %do this after plotSpk_
Error in irc>manual_ (line 5545)
S0 = plot_FigWav_(S0); % hFigWav %do this after for ordering
Error in irc (line 294)
    manual_(P);

**Comment by jamesjun** [comment]
Dear Weiss, thanks for reporting the error and thanks for your patience. The bug is now fixed. 
I am working on the new version (irc2) and the GUI will be developed for the new version shortly.

**Comment by WeissShahaf** [comment]
thanks James,
i pulled the commit but still get:

Reference to non-existent field 'fSpatialMask_clu'.
Error in irc>describe_ (line 5332)
    csDesc{end+1} = sprintf('    fSpatialMask_clu        %d', P.fSpatialMask_clu);
Error in irc>run_irc_ (line 28111)
detect_(P); sort_(P, 0); describe_(P.vcFile_prm);
Error in irc (line 230)
        run_irc_(P); 

this time it doesn't help to assign a value to fSpatialMask_clu.

and still manualk gui has the same issue:

Reference to non-existent field 'trWav_clu'.
Error in irc>plot_tnWav_clu_ (line 6203)
trWav_clu = ifeq_(P.fWav_raw_show, S_clu.trWav_raw_clu, S_clu.trWav_clu);%S_clu.trWav_clu%S_clu.tmrWav_clu
Error in irc>plot_FigWav_ (line 5909)
    S_fig = plot_tnWav_clu_(S_fig, P); %do this after plotSpk_
Error in irc>manual_ (line 5545)
S0 = plot_FigWav_(S0); % hFigWav %do this after for ordering
Error in irc (line 294)
    manual_(P); 



can i use irc2 for non .mda files (spikeglx recordings)?

**Comment by jamesjun** [comment]
I see fSpatialMask_clu being commented out. Could please you run “git stash” and “git pull” to make sure you have the latest commit?

-James

**Comment by WeissShahaf** [comment]
C:\Users\superuser\Dropbox\ironclust>git stash
No local changes to save

C:\Users\superuser\Dropbox\ironclust>git pull
Already up to date.

C:\Users\superuser\Dropbox\ironclust>

**Comment by jamesjun** [comment]
I moved my repository to flatironinstitute account from my personal account about a month ago. This might be why it's not updating. Please delete the folder and run "git clone https://github.com/flatironinstitute/ironclust.git"

**Comment by WeissShahaf** [comment]
i'm using version  irc version
v5.0.5 (10/14/2019) installed, MD5: 59611c7f8161d352085c5fe9ad1c9739

i deleted and recloned just in case.
now sorting runs.
but manual gui still does not.
 irc manual GL603_20191208_OF_g0_t0.imec0.ap_imec3b_staggered.prm
Reference to non-existent field 'trWav_clu'.
Error in irc>plot_tnWav_clu_ (line 6203)
trWav_clu = ifeq_(P.fWav_raw_show, S_clu.trWav_raw_clu, S_clu.trWav_clu);%S_clu.trWav_clu%S_clu.tmrWav_clu
Error in irc>plot_FigWav_ (line 5909)
    S_fig = plot_tnWav_clu_(S_fig, P); %do this after plotSpk_
Error in irc>manual_ (line 5545)
S0 = plot_FigWav_(S0); % hFigWav %do this after for ordering
Error in irc (line 294)
    manual_(P);

**Comment by WeissShahaf** [comment]
sorry, problem solved.
i was using github desktop to clone and update. once i did it in gitbash there were no issues anymore
thanks for the patience

**Comment by jamesjun** [comment]
I am glad the issue is resolved. You could use "irc update" command which
calls "git pull".

-James
